// Code generated by MockGen. DO NOT EDIT.
// Source: staycation/service (interfaces: StaycationUserService)

// Package service is a generated GoMock package.
package service

import (
	reflect "reflect"
	dto "staycation/dto"
	errs "staycation/errs"

	gomock "github.com/golang/mock/gomock"
)

// MockStaycationUserService is a mock of StaycationUserService interface.
type MockStaycationUserService struct {
	ctrl     *gomock.Controller
	recorder *MockStaycationUserServiceMockRecorder
}

// MockStaycationUserServiceMockRecorder is the mock recorder for MockStaycationUserService.
type MockStaycationUserServiceMockRecorder struct {
	mock *MockStaycationUserService
}

// NewMockStaycationUserService creates a new mock instance.
func NewMockStaycationUserService(ctrl *gomock.Controller) *MockStaycationUserService {
	mock := &MockStaycationUserService{ctrl: ctrl}
	mock.recorder = &MockStaycationUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStaycationUserService) EXPECT() *MockStaycationUserServiceMockRecorder {
	return m.recorder
}

// GetAllStaycationUsers mocks base method.
func (m *MockStaycationUserService) GetAllStaycationUsers() ([]dto.StaycationUserResponse, *errs.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllStaycationUsers")
	ret0, _ := ret[0].([]dto.StaycationUserResponse)
	ret1, _ := ret[1].(*errs.AppError)
	return ret0, ret1
}

// GetAllStaycationUsers indicates an expected call of GetAllStaycationUsers.
func (mr *MockStaycationUserServiceMockRecorder) GetAllStaycationUsers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllStaycationUsers", reflect.TypeOf((*MockStaycationUserService)(nil).GetAllStaycationUsers))
}

// GetStaycationUserById mocks base method.
func (m *MockStaycationUserService) GetStaycationUserById(arg0 string) (*dto.StaycationUserResponse, *errs.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStaycationUserById", arg0)
	ret0, _ := ret[0].(*dto.StaycationUserResponse)
	ret1, _ := ret[1].(*errs.AppError)
	return ret0, ret1
}

// GetStaycationUserById indicates an expected call of GetStaycationUserById.
func (mr *MockStaycationUserServiceMockRecorder) GetStaycationUserById(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStaycationUserById", reflect.TypeOf((*MockStaycationUserService)(nil).GetStaycationUserById), arg0)
}
